#
# Module manifest for module 'Edit-Module'
#
# Generated by: Bryan Dady
#
# Updated on: 7/3/2017   : Add Edit-Path and Open-PSEdit scripts (and their functions) to support using VS Code or another alternative editor. Renamed Fornmat-String function to Format-Path
# Updated on: 11/20/2017 : v2.3.0 - Combine previously independent FunctionFinder and Merge-Module (previously in PowerDiff.ps1) functions
# Updated on: 11/30/2017 : v2.3.1 - Merge in previously distinct PowerDiff.ps1 for copying/diffing/merging modules and scripts
# Updated on: 01/10/2018 : v2.3.2 - Refinement and output improvement to latest Merge-Module.ps1 (Previously known as PowerDiff)
# Updated on: 02/27/2018 : v2.3.3 - Removed personalized functions from Merge-Module.ps1 and my repository settings in Merge-Module.json
# Updated on: 04/06/2018 : v2.3.4 - Renamed variables (and corresponding JSON objects) with 'Diff' in their name to use naming-consistent 'Merge'
# Updated on: 08/24/2018 : v2.3.5 - Added Compare-PSEdit and Update-VSCode functions. Disable CompareDirectory / Compare-Directory.ps1 dot-souce references in Merge-Module.ps1
# Updated on: 01/02/2019 : v2.3.6 - Update Compare-PSEdit and Install-VSCode functions to work with VSCode-User (edition) instead of portable edition
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Edit-Module.psm1'

# Version number of this module.
ModuleVersion = '2.3.6'

# ID used to uniquely identify this module
GUID = '4c59e659-24f7-4370-88ac-1dbdcfdc2e63'

# Author of this module
Author = 'Bryan Dady'

# Company or vendor of this module
# CompanyName = 'Undefined'

# Copyright statement for this module
Copyright = '(c) 2015 Bryan Dady. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This started as a copy of Scripting Guy Ed Wilson''s Edit-Module function, from his PowerShellISEModule, and was updated to accommodate additional module file editing, such as those module elements added in more recent releases of PowerShell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('Compare-Directory.ps1', 'Edit-Path.ps1', 'Get-Function.ps1', 'Merge-Module.ps1', 'ModuleMember.ps1', 'Open-PSEdit.ps1', 'Repair-ModuleManifest.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Add-EnvPath', 'Assert-PSEdit', 'Compare-Directory', 'Edit-Module', 'Find-Function', 'Format-Path', 'Get-EnvPath', 'Get-EnvPathFromRegistry', 'Get-Function', 'Get-FunctionFile', 'Get-ModuleMember', 'Get-PSEdit', 'Initialize-Git', 'Merge-Repository', 'Open-AdminEditor', 'Open-PSEdit', 'Remove-EnvPath', 'Repair-EnvPath', 'Repair-ModuleManifest', 'Set-EnvPath', 'Test-EnvPath', 'Test-FileTypeAssociation', 'Test-LocalAdmin', 'Test-UserFileType', 'Test-UserProgID', 'Update-Repository')

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('Open-AdminEditor', 'PSEdit', 'Code', 'Init-Git')

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('Compare-Directory.ps1', 'Edit-Path.ps1', 'Get-Function.ps1', 'Merge-Module.ps1', 'Merge-Module.json', 'ModuleMember.ps1', 'Open-PSEdit.ps1', 'Repair-ModuleManifest.ps1')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @('PSModule', 'Edit-Module', 'Merge-Module', 'Open-PSEdit', 'Compare-Directory')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/bcdady/Edit-Module/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '01/02/2019 : v2.3.6 - Update Compare-PSEdit and Install-VSCode functions to work with VSCode-User (edition) instead of portable edition'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = @()

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

# SIG # Begin signature block
# MIIHqgYJKoZIhvcNAQcCoIIHmzCCB5cCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUE8WyPiICjgp0reRzpM79XmOe
# xy6gggTFMIIEwTCCA3WgAwIBAgIQKn06fomwQ6RKe8dq7JvZkjBBBgkqhkiG9w0B
# AQowNKAPMA0GCWCGSAFlAwQCAQUAoRwwGgYJKoZIhvcNAQEIMA0GCWCGSAFlAwQC
# AQUAogMCASAwgZgxCzAJBgNVBAYTAlVTMRAwDgYDVQQIDAdNb250YW5hMREwDwYD
# VQQHDAhNaXNzb3VsYTETMBEGA1UECgwKQnJ5YW4gRGFkeTEVMBMGA1UECwwMQ29k
# ZSBTaWduaW5nMRowGAYDVQQDDBFTZWN1cmUgUG93ZXJTaGVsbDEcMBoGCSqGSIb3
# DQEJARYNYnJ5YW5AZGFkeS51czAeFw0xODEyMzAwMzM5NDNaFw0xOTEyMzAwMzU5
# NDNaMIGYMQswCQYDVQQGEwJVUzEQMA4GA1UECAwHTW9udGFuYTERMA8GA1UEBwwI
# TWlzc291bGExEzARBgNVBAoMCkJyeWFuIERhZHkxFTATBgNVBAsMDENvZGUgU2ln
# bmluZzEaMBgGA1UEAwwRU2VjdXJlIFBvd2VyU2hlbGwxHDAaBgkqhkiG9w0BCQEW
# DWJyeWFuQGRhZHkudXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3
# tawJQoBbR3HJe+GYdZMLf0jhbO7FM0SoX8509y1RR62TTFsgnK2Aqa1SbzTysBMS
# rL0+MI6ud44lC7/qCSTcCoqIpSMGtJ56QxJ3lLcRBe5Xb4xDLvzitpaGeKlugHfd
# QAAd1w0SetXT3D/AjnzW0/WrYZ6in3I9FzFF+JC24t4PGyQUaeE6UgCtEVyOdRGA
# gRr1Xhz9jomUVw84qof4LAAdfroR1z7VgY8j2Mq66HzsY63/y9iiBJSOeQ+OvBuz
# 6aaBoiiOflQ0HxbZYXuj5HSWeRPaFa/cM2Vp1iBJQ0K0ptaS6pAx2yOngWKhTGUY
# OPaFRxELdUICyBrSWFdlAgMBAAGjgZwwgZkwDgYDVR0PAQH/BAQDAgeAMFMGA1Ud
# EQRMMEqgHQYKKwYBBAGCNxQCA6APDA1icnlhbkBkYWR5LnVzgQ1icnlhbkBkYWR5
# LnVzggt3d3cuZGFkeS51c4INYnJ5YW4uZGFkeS51czATBgNVHSUEDDAKBggrBgEF
# BQcDAzAdBgNVHQ4EFgQUZUQGb3yr7zNZSgdlXQEmJ9SpdjIwQQYJKoZIhvcNAQEK
# MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
# AKIDAgEgA4IBAQCe91LHEw1CznKDFzRP4zzRf8DL/ffFgkOPjnb3e1JYiuTTobii
# HQtrTBRxnRh3t5nYQOkAdQZRW/VY2cUopMnVvBo1iJKkosPyVvP+QeZ/V9J9kJR0
# cYUpiMXmFKB6JMfGCfHG+cN3t57HDC2+yXD/tkvF0DwKrIXVz6MJIAq6ww9ZLs+d
# 7dUYo1T4I8F3J28X5YBiBPTQ0W2or2CWfnTNwxzQavdrRFoPBaZgXTrkdIjCuI9G
# 4Tnl1lNfz5qCshSBhOrwwYUkTuZv32hcYe1Yuj2exBfEF3gT5Cbgrp25v37dRDZ5
# qmIb6V9gpxBxUlJp2ApxyCvvGOejlh6BhtaxMYICTzCCAksCAQEwga0wgZgxCzAJ
# BgNVBAYTAlVTMRAwDgYDVQQIDAdNb250YW5hMREwDwYDVQQHDAhNaXNzb3VsYTET
# MBEGA1UECgwKQnJ5YW4gRGFkeTEVMBMGA1UECwwMQ29kZSBTaWduaW5nMRowGAYD
# VQQDDBFTZWN1cmUgUG93ZXJTaGVsbDEcMBoGCSqGSIb3DQEJARYNYnJ5YW5AZGFk
# eS51cwIQKn06fomwQ6RKe8dq7JvZkjAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUhf9jgg5smDuJ
# gs1Qb7JSixxNy3kwDQYJKoZIhvcNAQEBBQAEggEANoy6h1bgT5pwzconyXoZQLni
# CIdAXyMNK3dwHahgskJhvv1YPKwkWYKHdXJjuexsH6/ky/7S+AuaGexECbmCOadV
# DKsXmrqq0ka7g6FC9Vv7cZL4/RifFuV6fCSUZlmvfc9nzjDi1yFCxm5oNNj/7CiE
# wsHSwwWMjcwfIHGH0ohLd1jYl361MVtayXnDb9mD9eLHq5yIZyiGz0kWdnxmTsAg
# ao5Nm68OVatkFBPRlVY1i3KTAYJehrw2Doageyuf5C6ME9ziaxD/OT0KY4ftK6sV
# q48HB/220eLHes4E62qh7OMPdkIfo9p+WDJIp1BbVpecVhHimZMDwLBnOkLXIw==
# SIG # End signature block
