#
# Module manifest for module 'Edit-Module'
#
# Generated by: Bryan Dady
#
# Updated on: 7/3/2017   : Add Edit-Path and Open-PSEdit scripts (and their functions) to support using VS Code or another alternative editor. Renamed Fornmat-String function to Format-Path
# Updated on: 11/20/2017 : v2.3.0 - Combine previously independent FunctionFinder and Merge-Module (previously in PowerDiff.ps1) functions
# Updated on: 11/30/2017 : v2.3.1 - Merge in previously distinct PowerDiff.ps1 for copying/diffing/merging modules and scripts
# Updated on: 01/10/2018 : v2.3.2 - Refinement and output improvement to latest Merge-Module.ps1 (Previously known as PowerDiff)
# Updated on: 02/27/2018 : v2.3.3 - Removed personalized functions from Merge-Module.ps1 and my repository settings in Merge-Module.json
# Updated on: 04/06/2018 : v2.3.4 - Renamed variables (and corresponding JSON objects) with 'Diff' in their name to use naming-consistent 'Merge'
# Updated on: 12/28/2018 : v2.3.5 - Disable CompareDirectory / Compare-Directory.ps1 references from within Merge-Module.ps1
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Edit-Module.psm1'

# Version number of this module.
ModuleVersion = '2.3.5'

# ID used to uniquely identify this module
GUID = '4c59e659-24f7-4370-88ac-1dbdcfdc2e63'

# Author of this module
Author = 'Bryan Dady'

# Company or vendor of this module
# CompanyName = 'Undefined'

# Copyright statement for this module
Copyright = '(c) 2015 Bryan Dady. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This started as a copy of Scripting Guy Ed Wilson''s Edit-Module function, from his PowerShellISEModule, and was updated to accommodate additional module file editing, such as those module elements added in more recent releases of PowerShell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('Compare-Directory.ps1', 'Edit-Path.ps1', 'Get-Function.ps1', 'Merge-Module.ps1', 'ModuleMember.ps1', 'Open-PSEdit.ps1', 'Repair-ModuleManifest.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Add-EnvPath', 'Assert-PSEdit', 'Compare-Directory', 'Edit-Module', 'Find-Function', 'Format-Path', 'Get-EnvPath', 'Get-EnvPathFromRegistry', 'Get-Function', 'Get-FunctionFile', 'Get-ModuleMember', 'Get-PSEdit', 'Initialize-Git', 'Merge-Repository', 'Open-AdminEditor', 'Open-PSEdit', 'Remove-EnvPath', 'Repair-EnvPath', 'Repair-ModuleManifest', 'Set-EnvPath', 'Test-EnvPath', 'Test-FileTypeAssociation', 'Test-LocalAdmin', 'Test-UserFileType', 'Test-UserProgID', 'Update-Repository')

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @('Open-AdminEditor', 'PSEdit', 'Code', 'Init-Git')

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('Compare-Directory.ps1', 'Edit-Path.ps1', 'Get-Function.ps1', 'Merge-Module.ps1', 'Merge-Module.json', 'ModuleMember.ps1', 'Open-PSEdit.ps1', 'Repair-ModuleManifest.ps1')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
         Tags = @('PSModule', 'Edit-Module', 'Merge-Module', 'Open-PSEdit', 'Compare-Directory')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/bcdady/Edit-Module/'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '12/28/2018 : v2.3.5 - Disable CompareDirectory / Compare-Directory.ps1 references from within Merge-Module.ps1'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = @()

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
